# Generated by Django 4.0.4 on 2022-04-20 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0002_product_total_cost_alter_product_funding_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='funding_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
