# Generated by Django 4.0.4 on 2022-04-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0003_product_created_at_product_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_price',
            field=models.IntegerField(),
        ),
    ]
